config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'

  get 'about', to: 'pages#about'

  get 'ask', to: 'pages#ask'

  get 'answer', to: 'pages#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def ask
  end

  def answer
    @answer = ''
    if params[:question] == 'I am going to work'
      @answer = 'Great !'
    elsif params[:question].last == '?'
      @answer = 'Silly question, get dressed and go to work!'
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Page About</h1>
<footer>
  <ul>
    <li><%= link_to "Go back to Home Page", root_path %></li>
  </ul>
</footer>

app/views/pages/answer.html.erb
<h1>Page Answer</h1>

<main>
<div id="question">
  <p><%= params[:question] %></p>
  <p class="italic">-You</p>
</div>
<div id="answer">
  <p><%=@answer %></p>
  <p class="italic">-You coach</p>
</div>
</main>

<footer>
  <ul>
    <li><%= link_to "Go back to Home Page", root_path %></li>
    <li><%= link_to "Ask again for ...", ask_path %></li>
  </ul>
</footer>

app/views/pages/ask.html.erb
<h1>Ask for something !</h1>

<main>
  <form action="/answer" data-turbo="false" method="get">
    <input type="text" name="question" placeholder="Ask for ...">
    <input type="submit" value="Ask!" id="button" >
  </form>
</main>

<footer>
  <ul>
    <li><%= link_to "Go back to Home Page", root_path %></li>
  </ul>
</footer>

app/views/pages/home.html.erb
<h1>Welcome !</h1>
<main>
  <ul>
    <li><%= link_to "Ask for something", ask_path %></li>
    <li><%= link_to "About us", about_path %></li>
  </ul>
</main>